# Generated by Django 3.2.10 on 2022-07-14 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название мероприятия')),
                ('description_short', models.TextField(verbose_name='Краткое описание мероприятия')),
                ('description_long', models.TextField(verbose_name='Длинное описание мероприятия')),
                ('longitude', models.FloatField(verbose_name='Долгота')),
                ('latitude', models.FloatField(verbose_name='Широта')),
            ],
        ),
    ]
