# Generated by Django 3.2.10 on 2022-07-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображения')),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='description_long',
            field=models.TextField(verbose_name='Полное описание мероприятия'),
        ),
    ]
