# Generated by Django 3.2.10 on 2022-07-14 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20220714_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='images', to='places.event', verbose_name='Мероприятие'),
        ),
    ]
