# Generated by Django 4.1 on 2022-08-06 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_event_options_alter_image_options_event_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ('-order',)},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('-order',)},
        ),
        migrations.AddField(
            model_name='image',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
