# Generated by Django 3.2.10 on 2022-08-11 10:39

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_event_options_alter_image_options_image_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=tinymce.models.HTMLField(verbose_name='Полное описание мероприятия'),
        ),
    ]
