# Generated by Django 3.2.10 on 2022-08-14 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0007_alter_event_long_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
        migrations.RemoveField(
            model_name='event',
            name='order',
        ),
    ]
