# Generated by Django 3.2.10 on 2022-08-16 21:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0008_auto_20220814_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='long_description',
            field=tinymce.models.HTMLField(blank=True, verbose_name='Полное описание мероприятия'),
        ),
        migrations.AlterField(
            model_name='event',
            name='short_description',
            field=models.TextField(blank=True, verbose_name='Краткое описание мероприятия'),
        ),
    ]
