# Generated by Django 3.2.10 on 2022-08-16 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0009_auto_20220816_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='event',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=9, verbose_name='Долгота'),
        ),
    ]
